### PR TITLE
Fix issue on FIPS with a SecurityManager in place

### PR DESCRIPTION
**Pull request by jerboaa**
Resolves: OPENJDK-1357

### CODE REVIEW

**Comment by jerboaa** [comment]
@martinuy @gnu-andrew Please review!

**Comment by martinuy** [comment]
@jerboaa Thanks for this contribution.

Can we also add read permission for "fips.nssdb.pin"? There is a read of this property from the jdk.crypto.cryptoki module, which probably has the same issue when a SecurityManager is installed in combination with an NSSDB that has a PIN.

**Comment by jerboaa** [comment]
> Can we also add read permission for "fips.nssdb.pin"?

Done in the update.

**Comment by martinuy** [comment]
I've been thinking a bit more about this issue and perhaps the best way is to elevate privileges for the automatic login, so we don't need to grant SecurityPermissions to SunPKCS11-NSS-FIPS for all modules.

Here it's a proposal for you to consider:

```
diff --git a/src/java.base/share/lib/security/default.policy b/src/java.base/share/lib/security/default.policy
index 3ee2ce6ea88..02bea84e210 100644
--- a/src/java.base/share/lib/security/default.policy
+++ b/src/java.base/share/lib/security/default.policy
@@ -142,6 +142,8 @@ grant codeBase "jrt:/jdk.crypto.cryptoki" {
     permission java.util.PropertyPermission "os.name", "read";
     permission java.util.PropertyPermission "os.arch", "read";
     permission java.util.PropertyPermission "jdk.crypto.KeyAgreement.legacyKDF", "read";
+    permission java.util.PropertyPermission "fips.nssdb.path", "read,write";
+    permission java.util.PropertyPermission "fips.nssdb.pin", "read";
     permission java.security.SecurityPermission "putProviderProperty.*";
     permission java.security.SecurityPermission "clearProviderProperties.*";
     permission java.security.SecurityPermission "removeProviderProperty.*";
diff --git a/src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java b/src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java
index f4d7c9cc201..1855e5631bd 100644
--- a/src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java
+++ b/src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java
@@ -160,10 +160,21 @@ public final class SunPKCS11 extends AuthProvider {
                          * fips.nssdb.path System property after expansion.
                          * Security properties expansion is unsupported.
                          */
-                        System.setProperty(
-                                FIPS_NSSDB_PATH_PROP,
+                        String nssdbPath =
                                 SecurityProperties.privilegedGetOverridable(
-                                        FIPS_NSSDB_PATH_PROP));
+                                        FIPS_NSSDB_PATH_PROP);
+                        if (System.getSecurityManager() != null) {
+                            AccessController.doPrivileged(
+                                    (PrivilegedAction<Void>) () -> {
+                                        System.setProperty(
+                                                FIPS_NSSDB_PATH_PROP,
+                                                nssdbPath);
+                                        return null;
+                                    });
+                        } else {
+                            System.setProperty(
+                                    FIPS_NSSDB_PATH_PROP, nssdbPath);
+                        }
                     }
                     return new SunPKCS11(new Config(newConfigName));
                 }
@@ -1433,6 +1444,7 @@ public final class SunPKCS11 extends AuthProvider {
         }
 
         @Override
+        @SuppressWarnings("removal")
         public Object newInstance(Object param)
                 throws NoSuchAlgorithmException {
             if (token.isValid() == false) {
@@ -1452,7 +1464,26 @@ public final class SunPKCS11 extends AuthProvider {
                  * property.
                  */
                 try {
-                    token.ensureLoggedIn(null);
+                    if (System.getSecurityManager() != null) {
+                        try {
+                            AccessController.doPrivileged(
+                                    (PrivilegedExceptionAction<Void>) () -> {
+                                        token.ensureLoggedIn(null);
+                                        return null;
+                                    });
+                        } catch (PrivilegedActionException pae) {
+                            Exception e = pae.getException();
+                            if (e instanceof LoginException le) {
+                                throw le;
+                            } else if (e instanceof PKCS11Exception p11e) {
+                                throw p11e;
+                            } else {
+                                throw new RuntimeException(e);
+                            }
+                        }
+                    } else {
+                        token.ensureLoggedIn(null);
+                    }
                 } catch (PKCS11Exception | LoginException e) {
                     throw new ProviderException("FIPS: error during the Token" +
                             " login required for the " + getType() +
```

**Comment by jerboaa** [comment]
@martinuy Sounds good. I wasn't liking the global grant for `authProvider.SunPKCS11-NSS-FIPS` anyway. Updated to your patch. Could somebody approve GHA workflows, please?

**Review by martinuy — APPROVED** [review]
Looks good to me.

**Review by gnu-andrew — APPROVED** [review]
Looks good to me too. Much preferable without the `FIXME`.

What do you mean by "Could somebody approve GHA workflows, please?"  You usually just enable them in your own fork.

**Comment by jerboaa** [comment]
@gnu-andrew nevermind that comment. It seems resolved now. The action runs are here:
https://github.com/jerboaa/jdk/actions/runs/3903513360

**Comment by jerboaa** [comment]
If you want this merged, Somebody needs to do it for me. I don't seem to have permissions. Just FYI :-)

**Comment by gnu-andrew** [comment]
> If you want this merged, Somebody needs to do it for me. I don't seem to have permissions. Just FYI :-)

Yeah, that's by design :) I've no problem merging it, but I'd like to see the tests pass first. Good to see they are running now. Thanks.

**Comment by gnu-andrew** [comment]
Tests have now passed.

**Pull request merged**
